feed_url = "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-g"

[route]
id = "2"
transfers = []

[station]
id = "125"
name = "59 St-Columbus Circle"
latitude = "40.768247"
longitude = "-73.981929"

[transfers]
stations = "['125', 'A24']"
