feed_url = "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-g"

[route]
id = "G"
transfers = []

[station]
id = "G35"
name = "Clinton-Washington Avs"
transfers = []
latitude = 40.6861
longitude = -73.98
